
// AUTH FLOW

export const AUTH_START = 'AUTH_START';
export const NOT_SIGNED = 'NOT_SIGNED';
export const AUTH_FAILED = 'AUTH_FAILED';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';


// ADMIN
export const ADMIN_HOME_DISPLAYS = 'ADMIN_HOME_DISPLAYS';

export const LIST_TEACHERS = 'LIST_TEACHERS';
export const ADDED_TEACHER = 'ADDED_TEACHER';
export const EDITED_TEACHER = 'EDITED_TEACHER';
export const DELETED_TEACHER = 'DELETED_TEACHER';

export const LIST_STUDENTS = 'LIST_STUDENTS';
export const ADDED_STUDENT = 'ADDED_STUDENT';
export const EDITED_STUDENT = 'EDITED_STUDENT';
export const DELETED_STUDENT = 'DELETED_STUDENT';

export const LIST_GUARDIANS = 'LIST_GUARDIANS';
export const ADDED_GUARDIAN = 'ADDED_GUARDIAN';
export const EDITED_GUARDIAN = 'EDITED_GUARDIAN';
export const DELETED_GUARDIAN = 'DELETED_GUARDIAN';

export const SUBJECT_TEACHER = 'SUBJECT_TEACHER';
export const SUBJECT_STUDENT = 'SUBJECT_STUDENT';

export const CLASS_TEACHER = 'CLASS_TEACHER';
export const CLASS_STUDENT = 'CLASS_STUDENT';

export const LIST_RANKS = 'LIST_RANKS';
export const ADDED_RANK = 'ADDED_RANK';
export const EDITED_RANK = 'EDITED_RANK';
export const DELETED_RANK = 'DELETED_RANK';

export const LIST_CANDIDATES = 'LIST_CANDIDATES';
export const ADDED_CANDIDATE = 'ADDED_CANDIDATE';
export const EDITED_CANDIDATE = 'EDITED_CANDIDATE';
export const DELETED_CANDIDATE = 'DELETED_CANDIDATE';


// TEACHER

export const TEACHER_HOME_DISPLAYS = 'TEACHER_HOME_DISPLAYS';

export const TEACHER_STUDENTS_CLASS = 'TEACHER_STUDENTS_CLASS';

export const TEACHER_CLASS_INFO = 'TEACHER_CLASS_INFO';
export const STUDENT_CLASS_INFO = 'STUDENT_CLASS_INFO';

export const STUDENT_CLASS_GRADES_INFO = 'STUDENT_CLASS_GRADES_INFO';
export const TEACHER_GUARDIAN_INFO = 'TEACHER_GUARDIAN_INFO';

export const TEACHER_ADDED_ASSIGNMENT = 'TEACHER_ADDED_ASSIGNMENT';
export const TEACHER_ASSIGNMENTS = 'TEACHER_ASSIGNMENTS';

export const EDITED_ASSIGNMENT = 'EDITED_ASSIGNMENT';
export const DELETED_ASSIGNMENT = 'DELETED_ASSIGNMENT';

export const TEACHER_SUBJECTS = 'TEACHER_SUBJECTS';

// STUDENT

export const STUDENT_BIO = 'STUDENT_BIO';
export const STUDENT_SUBJECTS = 'STUDENT_SUBJECTS';
export const STUDENT_GRADES_FOR_STUDENT = 'STUDENT_GRADES_FOR_STUDENT';
